# Site settings
title: Thibaud Maréchal
description: "Personal blog on bitcoin, stoicism and critical thinking."
url: "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—167986791-1

# Author
author:
  name: Thibaud Maréchal
  url: https://thibm.net
  email: hito@thibm.net

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: jekyll-tale
